export default {
  project: {
    ENTITY: 'project',
    FETCH_PROJECT_ALL: 'FETCH_PROJECT_ALL',
    FETCH_PROJECT: 'FETCH_PROJECT',
    CREATE_PROJECT: 'CREATE_PROJECT',
    MODIFY_PROJECT: 'MODIFY_PROJECT'
  },
  category: {
    ENTITY: 'category',
    FETCH_CATEGORY_ALL: 'FETCH_CATEGORY_ALL',
    FETCH_CATEGORY: 'FETCH_CATEGORY',
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    MODIFY_CATEGORY: 'MODIFY_CATEGORY'
  }
}