export default {
  project: {
    ENTITY: 'project',
    FETCH_ALL: 'FETCH_PROJECT_ALL',
    FETCH: 'FETCH_PROJECT',
    CREATE: 'CREATE_PROJECT',
    MODIFY: 'MODIFY_PROJECT'
  },
  category: {
    ENTITY: 'category',
    FETCH_ALL: 'FETCH_CATEGORY_ALL',
    FETCH: 'FETCH_CATEGORY',
    CREATE: 'CREATE_CATEGORY',
    MODIFY: 'MODIFY_CATEGORY'
  },
  ticket: {
    ENTITY: 'ticket',
    FETCH_ALL: 'FETCH_TICKET_ALL',
    FETCH: 'FETCH_TICKET',
    CREATE: 'CREATE_TICKET',
    MODIFY: 'MODIFY_TICKET',
    LOADING: 'LOADING_TICKET'
  },
}